export const projects = [
  {
    name: "MasterBrews",
    desc: "A platform bringing the power of Smart Contracts, NFT and Blockchain technology.",
    link: "https://masterbrews.cards/",
    techStack: "Gatsby, React, TailwindCSS, SASS",
    images: [],
  },
  {
    name: "Upvote",
    desc: "A platform for people to pogrammers and developers to ask and answer questions related to programming and software developement.",
    link: "https://upvote-f3f780338b93.herokuapp.com/",
    techStack: "PHP, Laravel, Vue, HTML, CSS, JavaScript, Linux.",
    fullTechStack:
      "PHP, Laravel, MySQL, Redis, HTML, CSS, JavaScript, Bootstrap, FontAwesome, WebPack, SASS, Algolia, Vue.",
    images: [
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-2.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-3.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-4.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-5.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-6.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-7.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-8.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-9.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-10.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-11.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-12.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555472/upvote/upvote-13.png",
    ],
  },
  {
    name: "FoodsPoint",
    desc: "Landing page for a food ordering website.",
    link: "https://riteshsahu.github.io/foodspoint/",
    techStack: "HTML, JavaScript, CSS, SASS, WebPack.",
    images: [
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555730/foodspoint/foodspoint.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555730/foodspoint/foodspoint-2.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555730/foodspoint/foodspoint-3.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555730/foodspoint/foodspoint-4.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555730/foodspoint/foodspoint-5.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555730/foodspoint/foodspoint-6.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555730/foodspoint/foodspoint-7.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555730/foodspoint/foodspoint-8.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555730/foodspoint/foodspoint-9.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555730/foodspoint/foodspoint-10.png",
      "https://res.cloudinary.com/dxdvk0bcy/image/upload/v1645555730/foodspoint/foodspoint-11.png",
    ],
  },
];
